version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: philmotecha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    depends_on:
      - db
    build: .
    ports:
      - 6969:6969
